.PHONY: all
all:
	gcc lab_9_1.c -lpthread -o lab_9_1.out
	gcc -pthread lab_9_2.c -o lab_9_2.out
	g++ -std=c++20 -pthread lab_9_3.cpp -o lab_9_3.out

.PHONY: clean
clean:
	rm lab_9_1.out
	rm lab_9_2.out
	rm lab_9_3.out
